// Renders the "sample ballot" summary as a downloadable/shareable PNG image.
// Pure canvas drawing - no external libraries, no network requests, no CSP changes needed.
const BallotCard = (() => {
  const LEVEL_ORDER = [
    'Federal', 'State', 'County', 'City/Town',
    'School Board', 'District', 'Special District', 'Neighborhood',
  ];

  const LEVEL_COLORS = {
    'Federal':          '#1a365d',
    'State':            '#234e52',
    'County':           '#744210',
    'City/Town':        '#1a202c',
    'School Board':     '#7c2d12',
    'District':         '#322659',
    'Neighborhood':     '#1a202c',
    'Special District': '#702459',
  };

  const FONT = '-apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif';

  function groupByLevel(officials) {
    const groups = {};
    officials.filter(o => !o.historical).forEach(o => {
      (groups[o.level] = groups[o.level] || []).push(o);
    });
    return LEVEL_ORDER
      .filter(level => groups[level]?.length)
      .map(level => ({ level, officials: groups[level] }));
  }

  function buildCanvas(officials, zip, geo) {
    const groups = groupByLevel(officials);
    const width = 1200;
    const padX = 64;
    const rowH = 46;
    const groupHeaderH = 56;
    const groupGapAfter = 28;

    let height = 210; // header band
    groups.forEach(g => {
      height += groupHeaderH + g.officials.length * rowH + groupGapAfter;
    });
    height += 90; // footer

    const scale = 2; // sharper output for sharing
    const canvas = document.createElement('canvas');
    canvas.width = width * scale;
    canvas.height = height * scale;
    const ctx = canvas.getContext('2d');
    ctx.scale(scale, scale);

    // Background
    ctx.fillStyle = '#ffffff';
    ctx.fillRect(0, 0, width, height);

    // Header band
    ctx.fillStyle = '#1a56db';
    ctx.fillRect(0, 0, width, 170);
    ctx.fillStyle = '#ffffff';
    ctx.font = `700 38px ${FONT}`;
    ctx.fillText('Your Sample Ballot', padX, 76);
    ctx.font = `400 22px ${FONT}`;
    const locLabel = `ZIP ${zip}${geo?.city ? ` · ${geo.city}, ${geo.stateAbbr}` : ''}`;
    ctx.fillText(locLabel, padX, 112);
    ctx.font = `400 16px ${FONT}`;
    ctx.fillStyle = '#dbe8fd';
    ctx.fillText('localvotes.app · Know who represents you', padX, 145);

    let y = 210;
    groups.forEach(g => {
      const color = LEVEL_COLORS[g.level] || '#1a202c';
      ctx.fillStyle = color;
      ctx.font = `700 21px ${FONT}`;
      ctx.fillText(g.level.toUpperCase(), padX, y);
      ctx.strokeStyle = color;
      ctx.lineWidth = 2;
      ctx.beginPath();
      ctx.moveTo(padX, y + 12);
      ctx.lineTo(width - padX, y + 12);
      ctx.stroke();

      y += groupHeaderH;

      g.officials.forEach(o => {
        ctx.fillStyle = '#1a202c';
        ctx.font = `600 20px ${FONT}`;
        ctx.fillText(o.name, padX, y);

        ctx.fillStyle = '#4a5568';
        ctx.font = `400 15px ${FONT}`;
        ctx.fillText(o.office || '', padX, y + 21);

        if (o.party) {
          ctx.font = `400 14px ${FONT}`;
          ctx.fillStyle = '#718096';
          const w = ctx.measureText(o.party).width;
          ctx.fillText(o.party, width - padX - w, y);
        }

        y += rowH;
      });

      y += groupGapAfter;
    });

    // Footer disclaimer
    ctx.fillStyle = '#a0aec0';
    ctx.font = `400 13px ${FONT}`;
    ctx.fillText(
      'Generated by LocalVotes from public government sources. Not affiliated with any government agency.',
      padX, height - 40
    );

    return canvas;
  }

  function toBlob(canvas) {
    return new Promise(resolve => canvas.toBlob(resolve, 'image/png'));
  }

  async function download(officials, zip, geo) {
    const canvas = buildCanvas(officials, zip, geo);
    const blob = await toBlob(canvas);
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `localvotes-sample-ballot-${zip}.png`;
    document.body.appendChild(a);
    a.click();
    a.remove();
    setTimeout(() => URL.revokeObjectURL(url), 1000);
  }

  // Returns true if a native share sheet was used, false if it fell back to download.
  async function share(officials, zip, geo) {
    const canvas = buildCanvas(officials, zip, geo);
    const blob = await toBlob(canvas);
    const file = new File([blob], `localvotes-sample-ballot-${zip}.png`, { type: 'image/png' });

    if (navigator.canShare && navigator.canShare({ files: [file] })) {
      try {
        await navigator.share({
          files: [file],
          title: 'My Sample Ballot',
          text: `Here's who's on my ballot for ZIP ${zip} — look up yours at LocalVotes.`,
        });
        return true;
      } catch {
        return false; // user cancelled - don't fall back to a download
      }
    }

    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = file.name;
    document.body.appendChild(a);
    a.click();
    a.remove();
    setTimeout(() => URL.revokeObjectURL(url), 1000);
    return false;
  }

  return { download, share, groupByLevel, LEVEL_ORDER, LEVEL_COLORS };
})();
