// city-council.js - looks up city/town council members from pre-built static JSON.
// Data is generated by: python local-officials-aggregator.py --state XX
// Stored at: data/{state_lower}_city_council.json

const CityCouncil = (() => {
  // Cache per state abbreviation: { MA: Promise<data|null>, ... }
  const _cache = {};

  async function _load(stateAbbr) {
    if (_cache[stateAbbr] !== undefined) return _cache[stateAbbr];
    _cache[stateAbbr] = fetch(`data/${stateAbbr.toLowerCase()}_city_council.json`)
      .then(r => (r.ok ? r.json() : null))
      .catch(() => null);
    return _cache[stateAbbr];
  }

  /**
   * Returns an array of official-card-compatible objects for the given city/state.
   * Returns [] if no pre-built JSON exists for the state (fetch will 404 silently).
   *
   * @param {string} city      - City name from zippopotam.us geo object
   * @param {string} stateAbbr - Two-letter state abbreviation (e.g. "MA", "NY")
   */
  async function lookup(city, stateAbbr) {
    const data = await _load(stateAbbr);
    if (!data || !data.city_index) return [];

    const indices = data.city_index[city.toLowerCase()] || [];
    const officials = [];

    for (const idx of indices) {
      const council = data.councils[idx];
      if (!council || !council.members.length) continue;

      for (const member of council.members) {
        officials.push({
          name:         member.name,
          office:       member.title || 'City Council Member',
          level:        'City/Town',
          party:        'Nonpartisan',
          phones:       member.contact_phone ? [member.contact_phone] : [],
          emails:       member.contact_email ? [member.contact_email] : [],
          urls:         council.website ? [council.website] : [],
          address:      [],
          channels:     [],
          jurisdiction: council.name,
        });
      }
    }

    return officials;
  }

  return { lookup };
})();
