// school-boards.js — looks up school board members from pre-built static JSON.
// Data is generated by: python local-officials-aggregator.py --state XX
// Stored at: data/{state_lower}_school_boards.json

const SchoolBoards = (() => {
  // Cache per state abbreviation: { MA: Promise<data|null>, NY: Promise<data|null>, ... }
  const _cache = {};

  // States that call it "School Committee" instead of "School Board"
  const _COMMITTEE_STATES = new Set(['MA', 'RI']);

  async function _load(stateAbbr) {
    if (_cache[stateAbbr] !== undefined) return _cache[stateAbbr];
    _cache[stateAbbr] = fetch(`data/${stateAbbr.toLowerCase()}_school_boards.json`)
      .then(r => (r.ok ? r.json() : null))
      .catch(() => null);
    return _cache[stateAbbr];
  }

  function _defaultTitle(stateAbbr) {
    return _COMMITTEE_STATES.has(stateAbbr) ? 'School Committee Member' : 'School Board Member';
  }

  /**
   * Returns an array of official-card-compatible objects for the given city/state.
   * Returns [] if no pre-built JSON exists for the state (fetch will 404 silently).
   *
   * @param {string} city      - City name from zippopotam.us geo object
   * @param {string} stateAbbr - Two-letter state abbreviation (e.g. "MA", "NY")
   */
  async function lookup(city, stateAbbr) {
    const data = await _load(stateAbbr);
    if (!data || !data.city_index) return [];

    const indices = data.city_index[city.toLowerCase()] || [];
    const officials = [];

    for (const idx of indices) {
      const district = data.districts[idx];
      if (!district || !district.members.length) continue;

      const contactUrl = district.board_page || district.website || null;

      for (const member of district.members) {
        officials.push({
          name: member.name,
          office: member.title || _defaultTitle(stateAbbr),
          level: 'School Board',
          party: 'Nonpartisan',
          phones: [],
          emails: member.contact_email ? [member.contact_email] : [],
          urls: contactUrl ? [contactUrl] : [],
          address: [],
          channels: [],
          jurisdiction: district.name,
        });
      }
    }

    return officials;
  }

  return { lookup };
})();
